#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
from dolfin import Constant, plot, interactive
import maelstrom.stokes_cartesian as sc
import maelstrom.problems as probs


def _main():
    mesh, W, P, u_bcs, p_bcs = probs.lid_driven_cavity()
    mu = 1.0
    u, p = sc.solve(W, P,
                    mu,
                    u_bcs, p_bcs,
                    f=Constant(('0.0', '0.0')),
                    verbose=True,
                    tol=1.0e-10
                    )
    plot(u, title='velocity')
    plot(p, title='pressure')
    interactive()
    return


if __name__ == '__main__':
    _main()
