#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  Copyright (c) 2012--2014, Nico Schlömer, <nico.schloemer@gmail.com>
#  All rights reserved.
#
#  This file is part of Maelstrom.
#
#  Maelstrom is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Maelstrom is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Maelstrom.  If not, see <http://www.gnu.org/licenses/>.
#
'''
This tool helps working around DOLFIN's inability to deal with SubMesh() in
parallel. It does so by explicitly extracting a submesh and writing it out to
a separate XML file. That file can then be read be the main routine.
'''

from dolfin import Mesh, MeshFunction, File, SubMesh
import os


def _main():
    args = _parse_args()

    # Read the mesh.
    mesh = Mesh(args.infile)

    base, ext = os.path.splitext(args.infile)
    subdomainfile = base + '_physical_region' + ext

    # Read the corresponding physical regions file.
    subdomains = MeshFunction('size_t', mesh, subdomainfile)

    submesh_workpiece = SubMesh(mesh, subdomains, args.submesh_id)

    # Now write subdomains out to an XML file again
    outfile = File(args.outfile)
    outfile << submesh_workpiece
    return


def _parse_args():
    '''Parse input arguments.'''
    import argparse
    parser = argparse.ArgumentParser(description='Read and write a DOLFIN'
                                                 'mesh function.')
    parser.add_argument('infile',
                        help='Input mesh filename with subdomains',
                        type=str
                        )
    parser.add_argument('submesh_id',
                        help='Submesh to extract',
                        type=int
                        )
    parser.add_argument('outfile',
                        help='Output submesh file',
                        type=str
                        )
    return parser.parse_args()


if __name__ == '__main__':
    _main()
