#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
'''
This tool is to work around bug

    https://bugs.launchpad.net/dolfin/+bug/991905
    https://bitbucket.org/fenics-project/dolfin/issue/174/dolfin-convert-dumps-gmsh-facet-regions-in

by reading a mesh function file and dumping it in the same location, implicitly
converting it into a format readable in parallel.
'''

from dolfin import Mesh, MeshFunction, File
import os


def _main():
    args = _parse_args()

    # Read the mesh.
    mesh = Mesh(args.meshfile)

    base, ext = os.path.splitext(args.meshfile)
    subdomainfile = base + '_physical_region' + ext

    # Read the corresponding physical regions file.
    subdomains = MeshFunction('size_t', mesh, subdomainfile)

    # Now write subdomains out to an XML file again
    outfile = File(subdomainfile)
    outfile << subdomains

    return


def _parse_args():
    '''Parse input arguments.'''
    import argparse

    parser = argparse.ArgumentParser(description='Read and write a DOLFIN'
                                                 'mesh function.')

    parser.add_argument('meshfile',
                        help='Input mesh filename'
                        )

    return parser.parse_args()


if __name__ == '__main__':
    _main()
